language: generic
sudo: required

services:
  - docker

before_install:
  - docker build -t 2345512/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true 2345512/docker-react npm run test
                                                                                                                                      
~                                    
