sudo: required
language: generic
services:
  - docker

before_install:
  - docker build -t 2345512/docker-react -f Dockerfile.dev .

script:
  - docker run 2345512/docker-react npm run test -- --coverage
